# -*- coding: utf-8 -*-
"""request.ipynb
Automatically generated by Colaboratory.
Original file is located at
    C:\xampp\htdocs\BIML\House-Price-Predictor-master\Data
"""

import requests

url = 'http://localhost:5000/predict_api'
r = requests.post(url,json={'House_Price})

print(r.json())
