# -*- coding: utf-8 -*-
"""request.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/19FoicCK8Ig3Yj7tVG_zSdCaDXBAph23H
"""

import requests

url = 'http://localhost:5000/predict_api'
r = requests.post(url,json={'Angka Melek Huruf Penduduk Umur 15-24 Tahun Menurut Provinsi	':99, 'Angka Partisipasi Sekolah ( A P S )':82})

print(r.json())
